# Generated by Django 2.2.10 on 2020-05-14 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostManager',
        ),
    ]
