# Generated by Django 2.2.10 on 2020-06-19 21:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200610_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='incredient_pdf',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='unlikes',
            field=models.ManyToManyField(blank=True, null=True, related_name='unlikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
